### ISSUE TITLE
GGMax Bug - DevTest - Frame rate fluctuations.

### ISSUE THREAD

**Issue by davetgc** [Dark-Basic-Software-Limited/GameGuruRepo#5907]
I'm seeing some very inconsistent results in performance with FPS ranging between 140fps with sudden drops to 80fps with Vsync off.

With Vsync on the jumps are stranger, with MAX hovering around 57fps, but dropping as low as 30fps 

Both of these are causing major jarring and sometimes causes freezing for a few seconds, dropping to 0fps. This issue seems to be fairly recent.

Update: Restarting MAX seems to reduce the jarring, which make me think there could be a memory leak somewhere.

[Vsync on](https://youtu.be/3hASw2zAPm0)

[Vsync off](https://youtu.be/z7lJPx5-YC0)

**Comment by PalmTree11** [comment]
I may have posted this is the wrong place. My issue is the frame rate fuctations as described in that thread. 
HP Pavilion
AMD Ryzon 7 5800H
Ram 16 GB
Nividia GeForce GTX 1650

**Comment by LeeBamberTGC** [comment]
@davetgc New DEVTEST build with both performance fixes and memory leak fixes, so might have resolved this one.  If not, can you keep VSYNC ON and let me know in what scenarios a 60fps drops to 30fps, as this should not happen unless there is a million tonne polygon dragon behind you :)

**Comment by davetgc** [comment]
Hi Lee,

The new devbuild is better, but it's still happening.

It's a hard one to replicate as it's not always consistent. Sometimes MAX
will freeze at a certain point for a few seconds, and a second run through
it'll be fine at the same point.

One very obvious drop is when characters are spawned from trigger zones,
when there can be a pause for a second or two. This is only apparent in
larger levels.

I'll keep an eye out for more.

**Comment by Kitakazi** [comment]
Hey I've been having this problem too. Probably started for me around the time davetgc posted this thread. 
Max will randomly freeze completely for a couple of seconds. This happens in the editor and in test game. And it seems after the latest updates the problem is getting worse and worse.

**Comment by LeeBamberTGC** [comment]
@Kitakazi What DEVTEST build are you running right now?

**Comment by Kitakazi** [comment]
I will update with the exact build when I get home from work later today, but it is the most recent as of yesterday.

**Comment by mike123yy** [comment]
I've been getting bad frame rates lately with the new Dev test and even the retail build but not as bad.  I've been doing a lot of optimizations to try to fix it but nothing seems to be bringing the frame rate up.  I did turn on the memory and vram monitor and noticed once I open the program everything I do makes both of them go up.  Even after closing the level they stay at high levels and then once you open up another level they keep going up.  They don't even drop once you go out into the main menus.  I'm assuming these are calculated in GB and if that's so it's maxing out my memory and getting up there on the vram.  Here's some screenshots of it going up.  I assume this might be the same cause contributing to the performance issues I'm having as well as above

![Image](https://github.com/user-attachments/assets/da486c19-f979-4b57-a323-84a3e2789cb7)

![Image](https://github.com/user-attachments/assets/16ee3d00-0ed4-4f80-8dfc-210956aae9fd)

**Comment by LeeBamberTGC** [comment]
@Kitakazi @mike123yy Am I right in describing this performance issue as running the game and getting [1] as described below:

1. You get 58-60fps most of the time, and then for no reason, the performance drops hard for a half second or so, causing a stutter in the smoothness of the game, and then restores and carries on as normal.  As though something was being processed in the game loop that took WAY more than the maximum 16ms allowed for the entire cycle and thus caused a stop-start feel to the proceedings?

2. Or is it a consistent sub-60fps framerate, like say 30-40 when you expected 60fps?

3. Or you are running normally around 60 fps, and then there are several seconds (3-6 seconds) where the game seemingly stops to a crawl (1-20fps) and then resumes as normal back up to 60 fps.

Each of these descriptions is a different underlying cause so have a think about which one best describes what you see, and if you can also provide a video with the latest DEVTEST build too (GameGuru MAX Build 02-05-2025-20-12 ) showing the typical level under load and the performance stutter, that would also help form a clue or two.

**Comment by mike123yy** [comment]
That being the case my performance issue might be different than these guys. My performance is tanking pretty consistently. I made a video for you as requested. I tried lowering all the settings and turning off shadows and anything I could think of to get the performance to jump but it stays consistently low. I also changed my screen resolution to 1080 P when I'm normally running at 4K and the frame rate is exactly the same between both resolutions. I mentioned above about the memory usage up at the top right. Even after leaving the level it stays at the same usage which you can see in the video. I also noticed when I click the little head icon to go into logic mode the performance goes down to about 10 frames per 2nd to 20. I forgot to include that in the video. I don't know if that gives any clues…one other thing I forgot to put in the video is if you stare at the ground or the sky the frame rate doesn't change which you figure it normally would since it's not rendering any of the objects on screen. unless the object culling isn't working

https://youtu.be/LeQJ3P1Ktoc

Processor	AMD Ryzen 9 5900X 12-Core Processor, 3701 Mhz, 12 Core(s), 24 Logical Processor(s)
Installed Physical Memory (RAM)	32.0 GB
Graphics card 6590xt
1tb ssd

**Comment by Kitakazi** [comment]
When I posted my comment I was talking about #3 kinda... - the entire program would freeze for 1-5 seconds completely unresponsive. However, I have not had it happen since yesterday. And it was happening at least once every 15minutes...so since I havent had it happen since yesterday... I think that is good now. 

But I definitely also have experienced #1 really bad recently where I am getting some standard frame rates then as you say the performance drops hard for a half second or so, causing a stutter in the smoothness of the game. And tbh the framerates seem lower overall than week or two ago. Below is a video from a level im working on. My monitor refresh rate is 165 btw. 

In the the first clip, the stutter is caused by the music zone activating running the script ambienceinzone.lua 

https://youtu.be/csgNoneaUzc?si=8YSGdxVURZHRinvY



Maybe we all posting different versions of frame rate fluctuations sry. 
specs 
RTX 4080 
13th Gen Intel(R) Core(TM) i7-13700KF, 3400 Mhz, 16 Core(s), 24 Logical Processor(s)
32gb DDR5

**Comment by LeeBamberTGC** [comment]
@Kitakazi Thanks for the 2 videos, very revealing.  I cannot decide between memory cache swapping or some logic bombs that are eating up available per-cycle milliseconds.  I could find out by running your game through OPTICK profiler that MAX supports (or did the last time I used it over a year ago). If you find time, can you make a standalone of the level in the second video and I will compile locally and run through OPTICK and see where the performance dives hit, and trace it to the cause (if I can repeat on my system). As I am using a very old AMD card, it SHOULD reproduce these stalls (if not more so).  Thanks for your help!  P.S. AWESOME looking game there!!

**Comment by thatmodelguy** [comment]
I think I'm starting to suspect that the performance issues I'm getting and may be the same for these guys might be tied to logic. I was just doing a test with my mid-evil game on the second level. As of the moment it barely has any NPC's mostly scenery but I had torches set up leading the way to the final castle. With the level as it was I was getting about 90 FPS and then I made the torches with particles. Not much difference. I ran out of available particles for the fog I was going to do so I decided to change the torches from using particle fire to using the fire decal with the decal facing script. Placing the decal torches in the same exact spots made the frame rate tank to about 43 FPS. I'm no expert but I would assume its because all of them are having to run scripts now.
I also have a pretty big level in my first game with tons of assets but very little going on in the way of scripts and run superfast. Then I have another level that's very small but runs a lot of logic and it's very heavy on the system and gets a lower frame rate. My mid-evil game main level consists of mostly scenery besides the key locations and a bit of NPC's but it has a lot of scripts because it's open world and about nine different cut scenes throughout the level which all use a bit of logic. If you toggle logic on it cuts the frame rate in half. Like I said, I could be wrong but it seems to be a pattern

**Comment by LeeBamberTGC** [comment]
@Kitakazi, I broke out OPTICK to help me find all your performance spikes in the demo game you sent me. It revealed much:

![Image](https://github.com/user-attachments/assets/1dc0875c-4603-46a2-8676-57cc83ea76f4)

The CPU Side:
I first separated out the engine/logic side from the graphics side. I found issues in the weapon and ammo logic, overusing intersect collision checks, I found the ambienceinzone was a real perf hit as it tried to reset all sound volumes (twice) and just to make sure no other scripts had drain spikes I have added a new producelogfiles=3 feature that will message you during testing if any one LUA call takes too long.  I also fixed the issue of the manual UV data system taking WAY too long for what it was doing, now it is applied more sparingly so let me know if your texture changers are affected.  With those fixes, I eliminated ALL logic perf hit spikes in your demo level, which meant when running with the camera distance set to the nose on your players face, it ran smoothly on my ancient GPU :)  The remaining lowest hanging fruit now is the intersectall call, which for things like picking up weapons and ammo using the pinpoint method is still expensive, and I would like to find a quicker way to do this without doing a crazy massive scene raycast just to know that you are indeed in front of a button/weapon/thing within arms reach :)

![Image](https://github.com/user-attachments/assets/a3fb9fc0-862b-40fe-9a14-1a5f38102efc)

The GPU Side:
The second and more challenging issue was on the graphics side, with the majority of the perf hits happening as the graphics were handled.  Again, I used OPTICK to see into the heart of this:

![Image](https://github.com/user-attachments/assets/d854aade-fd84-4be0-9ceb-2a4744be37dc)

As you can see, just staying in the elevator and quickly twizzing around the camera angle at full camera distance set gave Wicked Engine of old something to get a headache over.  My next step now is to detail what is inside those purple bars and find out which sections are causing the most grief.  Will post here when I know more (probably in a few hours) :)

**Comment by Kitakazi** [comment]
Hey Lee, this is awesome, thank you so much for digging into it. I really appreciate you taking the time to isolate both the logic and graphics-side issues and even patching things like the ambience zone and UV handling. That producelogfiles=3 tip is going to be super useful going forward too. 
I'll make sure to test the changes on my end and report back, especially the texture changers. Thanks again for helping squeeze more performance out of this beast.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Additionally fixed the issue with the camera far distance messing up, will retain the distance you set for it now :)  You had the right idea by setting the camera distance to suit the level you designed, your instincts are bang on!  So, onto the graphics...

The GPU Side:
After much additional events added to OPTICK to track why the GPU stalls and stutters, it turns out that the MASSIVE time taken to Present the frame for rendering is down to the size of the combined textures on the screen at the time.  Textures are mostly cached, and are pulled up to the front when they are needed for rendering.  When you move around the level, newer textures are needed and so these are pulled in and the older ones discarded. This takes some GPU time to move the textures about, but subsides very quickly once the transaction is complete. The problem is that depending on how much Video Memory your graphics card has, the GPU runs out of first level cache memory to store the textures and discards some to make room for others, this causes the stutter you see on screen.  That is why fast camera rotations are the worst as they sweep across a LOT of texture potential and tries to pull and render the lot, all at once. Ouch!

It's 2 AM so calling it a night here, but I have prepared and emailed your demo back to you with some sizable chunks taken out of your texture files and texture file sizes, plus some other tweaks such as disabling the terrain system and reducing the MSAO setting as that would pull more and larger LOD textures into the mix.  There are two solutions, the first is undesirable, which is to simply squash the sizes of all the textures at every opportunity so the footprint of textures scoped out in any scene spanning the 1500 units distance being rendered fits well within a typical 4GB video memory card.  In this way, swinging the camera angle around cannot cause texture swap thrashing, and then gentle progress through movement in the level would produce unnoticeable swaps.

The second solution and the one MAX needs to do, is to take care of this automatically on behalf of the game developer :)  Maybe one day you might want to sit down and work out your texture caching budget through every level of every game you make, and if you work for the AAA games industry, get ready to roll your sleeves up for that lovely task!  In the meantime, lets see if MAX can come up with a few tricks to have our cake and eat it.

It occurs to me that we only need the highest resolution textures within any current local camera scope, and can probably show a dynamic budget for this when testing the level. If we can keep the current 'score' below our budget, no swapping is required and so no stuttering will happen.  Maybe base this on 4GB being the minimum, and then we can increase the budget by 2GB chunks for users with nicer graphics cards and want the best visuals.

I am also suspicious of the fact that maybe its not just the size of textures being cached about, but the number of times the draw calls demand the texture references to be swapped in. We already group draw calls by texture, but too many different textures per cycle might also cause a secondary stutter not related to caching.  I kinda proved this when I used the new "dividetexturesize=0" in SETUP.INI to make ALL the game textures the same texture and the resulting game play was OH SO SMOOTH (but not very good to look at naturally).

@plemsoft Can you remember the current state of our geometry batching system for MAX?  I think this is still active in the engine, and automatically handles the grouping of matching textured meshes together to render as a single draw call, but there might be an enhancement opportunity to find smaller static geometries that use 2-4 different textures, combine those textures into a single larger texture, and then batch all four groups into one super group rendered with one draw call and one larger texture.  Reducintg draw calls and texture switching in one go, and may resolve one of the several causes of large level stutter.

I am sure there will be more ideas to help defeat stutter once and for all, but its great to know there is a TOP demo game we can test these ideas out on!

**Comment by plemsoft** [comment]
@Kitakazi Try setting "shadows->point lights->0" and check if this stop the stuttering. When I test standalone games this is normally what is wrong and produce the stuttering. 
The problem with this and why we can't occlude point light is that when a point light is outside the frustum and you rotate the camera , in the distance perhaps 16 point light goes from out frustum to in frustum In this case we can't use occlusion culling of the point light as its based on the prev. frame data where they was out of frustum and so are not in the prev. frame data, so they all need to update , that would mean 16 * 6 additional frame renderings, and give that stuttering. After this when they are in frustum they can be occlusion culled normally again and act normal.
The solution to this problem is to bake the point light shadows so we are able to delay update them based on the distance, last time I tried this I got flickering shadows so its still a WIP. @LeeBamberTGC The test code for this is in the wicked repo.

@LeeBamberTGC The state of the batching is in a good state, as you can see in the video, it only use from 40-350 draw calls, and only 79 drawcalls for ALL shadow rendering. This is actually pretty good. But yes perhaps it could be optimized more.
To check if its caused by texture swapping, Make a copy of the standalone (note the vram usage) , then run "Max Standalone Optimizer" , set ALL max texture sizes to 32x32 and run it. Now check the new standalone and see the result, this will eliminate the texture swapping issue so you can see from that, what else the problem could be. Not sure what "the new dividetexturesize" is perhaps it do the same ? if it is you could try to convert all textures to first 2048x2048 check if the stuttering is gone, if not set it to 1024x1024 and try again , this will give a good indication of what textures need to be reduced I think that the 4096x4096 textures we use in many places are the problem, so setting a max of 2048x2048 properly fix it.

Not sure what demo game your using for testing. but if its Screos I got it and we have actually used it for making most of the optimizing like occlusion culling ... I even converted it to the latest DX12 version at the time so we could test if that would solve the stuttering, but luckily it did not it had the same problems as our DX11 version with culling (That we fixed in our dx11 version), so upgrading to DX12 for that, would not have giving us anything so luckily Lee did not spent a year on that :)

![Image](https://github.com/user-attachments/assets/e567d6c1-035c-480f-8937-5868e6b9b833)

Let me know if using 0 point lights stop the stuttering ? :)

**Comment by davetgc** [comment]
Hi Preben,

I still get freezes and stuttering without any point lights, so I don't
think that's solely the issue. I think it's more likely to be behaviors but
aren't sure. The strange thing is it's not consistent. A level will stutter
or freeze at a point during testing, but on another run, not freeze or
stutter at that same point. Sometime it'll run for awhile smoothly and then
suddenly slow down without any changes.

**Comment by Kitakazi** [comment]
@plemsoft 
I will send you the level I sent to Lee.

**Comment by LeeBamberTGC** [comment]
@Kitakazi @plemsoft Thanks for the follow-up info!  Settings lights (and thus shadows) was one of the first things I tried, basically reducing everything to zero and still got the stutter. It was only when I used my new "dividetexturesize=0" feature in the latest build (which makes ALL the game textures the same 256x256 texture) did the stuttering completely disappear :)  This then lead me to the idea of the texture resources causing too much back-end cache work that caused the "Present" action when rendering spike to incredible numbers (150ms-1200ms was normal).  @Kitakazi Thanks for the new media files for the demo, I will use this to test the theory of the textures using @plemsoft amazing standalone optimizer and try a few other things.

@Kitakazi I can also definitely confirm that the ambientinzone WILL have caused stutter as it had a function inside that call which reset every sound volume in the level :)  I have fixed this in the next DEVTEST build and will confirm with OPTICK that this CPU side spike is not the reason for future stuttering with your demo.

Expect a new DEVTEST you can play with later today!

**Comment by LeeBamberTGC** [comment]
@Kitakazi Also adding in some more fixes that will correct any old DBO model files attempting to use absolute paths to textures, meaning any changes to your level assets for the standalone will draw from those asset files properly (such as when using Prebens Standalone Optimizer), and will also clean up any other rogue use of absolutes in any model loaded in:

![Image](https://github.com/user-attachments/assets/b4f2a63c-cfe6-44d8-8d4a-5efb7e2875cd)

**Comment by LeeBamberTGC** [comment]
@Kitakazi I have emailed you a new demo export for you to try, let me know if this reduced standalone still stutters, thanks!

**Comment by LeeBamberTGC** [comment]
@Kitakazi I have a further demo to send you, in the meantime I think we can narrow down the stutters to the GPU side of things now. I ran through much of the level with my reduced texture demo, and the CPU stayed well within the threshold for typical cycles. The GPU on the other hand showed some interesting things:

![Image](https://github.com/user-attachments/assets/8f36d665-e0e9-4b4b-a08b-6e05419cfa0e)

The new bracket values in the performance data are the peek values that element reached (and can be reset by exiting and entering the performance tab), and shows some elements that do a LOT of work for one or two frames when the camera rotates sharply. I would have explained it with the light/shadow recall, but I switched all point lights off for this run through, so something related or similar is causing this work.

Not sure what that would be, and it could be we find it as the point light shadow code is improved, but the stutters are now very infrequent and could be lived with for now.  I will improve the demo textures slightly and send you my latest version of your demo. The DEVTEST build also includes the fixes and tweaks used for your demo too :)

**Comment by Kitakazi** [comment]
Hey I just finished testing the latest version of the level you sent and performance was super smooth, I didn’t hit any stutters during normal gameplay or fast camera movement. Definitely confirms that the stutter is tied to texture load and memory churn on the GPU.

That peek timing data in the performance overlay is really helpful for tracking what’s flaring up. Even with point lights disabled, I still saw some spikes during quick rotations, nothing disruptive, but clearly some deeper render-side behavior is still kicking off in those moments.

Thanks again for all the deep-dive work and insight. Ill scope out the latest DEVTEST and test it out a bunch this week.

**Comment by plemsoft** [comment]
@LeeBamberTGC Took a look at the demo level, found a few things.

* The old pMesh->pOriginalVertexData was still allocated with anything where bone count > 0 , saved some mem there.

* Standalone with _e_ files never used this but always resolved to the document folder with the original files (made it hard to check optimizing of the _e_ files).

* The demo had 263 .PNG files , we need to eliminate them , added a feature in MAX Standalone Optimizer v1.2 to convert all known png files to dds , there was also many 4096x4096 png's that use 64mb each compared to bc1 8 mb. so its a huge mem saving (it do alpha scan so always select correctly between bc1 or bc3).

If you download the new 1.2 version: https://www.patreon.com/PLEMSOFT/shop/gameguru-max-standalone-optimizer-v1-2-152818?source=storefront
And run it with "Convert known PNG files to DDS", it will convert them all.
After that you need to merge the latest changes , or it will not work , need the new prefer dds over png feature:
https://github.com/TheGameCreators/GameGuruMAX/pull/55

**Comment by LeeBamberTGC** [comment]
@plemsoft Okay, new DEVTEST build uploaded and new commit made to repo. With this, you can take the latest SCREOS project, save standalone, run your optimizer on it using 1K+512+256+256 settings, run the demo, drop point shadows to 256 resolution, and it runs pretty smoothly. Those pesky PNG textures really hurt the GPU it seems, nice find there!  I would say once the shadow and WParticle hits are smoothed out, nearly all the stutter would be gone :)

@Kitakazi I will email you my latest build of your demo. A few more optimizations and I think you will be good to continue your project without the stutter.  I ran through the whole level and I think its just the WParticles and Shadow work that cause the stutter now, and my next target :)

![Image](https://github.com/user-attachments/assets/1164f59f-45dc-4889-9ea9-1396538775dd)

@plemsoft In the shot above, you can see the high spots that relate to the WParticles and Shadow work. In the demo I have delayed shadows switched off, and we might look at an even more aggressive delay that forces the work to be spread out so it never exceeds a preset MS count per cycle.

**Comment by plemsoft** [comment]
@LeeBamberTGC There is a problem with WParticle Simulate , there is no emitterbank and in the standalone so only impact effects are loaded, there should not be any simulation when you dont see a effect , I have a look at this and get back :)

**Comment by plemsoft** [comment]
@LeeBamberTGC Problem with WParticle Simulate is fixed , will take another look at the delayed point shadows, in your screenshot point and directional shadows is not separated , but I think its the point that cause the delays, directional can already be set to "delayed" 2 - 3 cascades per frame or "laptop" 1 cascade per frame :)
https://github.com/TheGameCreators/WickedRepo/pull/21
https://github.com/TheGameCreators/GameGuruMAX/pull/56

**Comment by plemsoft** [comment]
@LeeBamberTGC Got delayed point shadows working , it is in the same pull as above. will follow the "Delay Shadows" and "Laptop" options (also bases on distance) :)

**Comment by LeeBamberTGC** [comment]
@plemsoft new commits in latest DEVTEST build and looking good!  My latest export of the SCREO standalone shows no stutters any more, the only thing I needed to do was drop the size of some textures using your standalone optimizer so the level fits into my 4GB AMD oldie-card.  Modern games would do this reduction automagically as the level loads in, but we can look at that in the future as a separate thing. I had something similar back in the day for FPS Creator that would check the size of video memory, then slap on a general division of texture size as the file is loaded in. As all cards were pretty nasty back then, it was a requirement for most games!
