### ISSUE TITLE
GGMax Bug - Raising water level in terrain generator crashes my AMD drivers

### ISSUE THREAD

**Issue by boltactiongaming** [Dark-Basic-Software-Limited/GameGuruRepo#6184]
As simple as it sounds. I was adjusting a terrain map, Got it how I wanted, then as I began to raise the water, the drivers crashed.
GGM Crashed, and generated a log.

[Guru-Crash.log](https://github.com/user-attachments/files/22916871/Guru-Crash.log)

**Comment by LeeBamberTGC** [comment]
@boltactiongaming Yes, this is a known issue with the latest AMD drivers since March 2024 (or might even be 2023). I fixed a few issues that the newer drivers created, but I am sure there are more deeper ones and it sounds like you are hitting them.  Try rolling back your AMD driver all the way back to the March driver from last year, see if that avoids the crash you are seeing (and to confirm it is the same driver issue I encountered previously).  Eventually, a DX12 version of the engine would resolve this for AMD cards as it relies on a completely different architecture.

**Comment by boltactiongaming** [comment]
Unsure will test and update later.

**Comment by LeeBamberTGC** [comment]
@boltactiongaming Thanks for the quick response!  I have uploaded a new DEVTEST that adds extra precautions around the code that attempts to bind a "bad" BindUAV resource. Maybe this will help stop the crash, though it may introduce other artefacts..

**Comment by LeeBamberTGC** [comment]
@boltactiongaming Thanks for the DMP and CRASH.LOG files, they helped me find a key :)  Check out the new DEVTEST build that should avoid this specific crash and also add some extra logging (roughly for now) to see if that does the trick.  As I build up more knowhow in finding these more obscure issues, I can hopefully design an even better crash reporter that can spit out the smoking gun much quicker in 2026, it should help hugely as the community move towards releasing actual MAX games :)

**Comment by boltactiongaming** [comment]
We'll get there - especially with more detailed logging.  However - still having problems :( 
This time I loaded my heightmap file and went to move the viewscreen area (first thing I clicked on) and it instantly crashed.

[Guru-Crash.log](https://github.com/user-attachments/files/24417815/Guru-Crash.log)
[Guru-MapEditor.log](https://github.com/user-attachments/files/24417814/Guru-MapEditor.log)
[crashdump.dmp](https://github.com/user-attachments/files/24417813/crashdump.dmp)

**Comment by boltactiongaming** [comment]
@LeeBamberTGC ok so this was a weird one. Same process as previous.
Open heightmap file (see above notes)
resize several times, as soon as I hit the heightmap bar, it crashed.

how it differed:
Got the wicked error, like usual.
Screen went black, cycled about 8 times.
Came back, GGM never crashed. It just stayed open with a white screen. Eventaully got this error:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/402a5524-df23-4002-a8f4-483ae6bafc3d" />

only log file created was ggm map editor:

[Guru-MapEditor.log](https://github.com/user-attachments/files/24755539/Guru-MapEditor.log)

Windows event viewer shows:
event 4101, Display: Display driver amduw23g-196283-af4b12f4 stopped responding and has successfully recovered.

**Comment by LeeBamberTGC** [comment]
@boltactiongaming I have added some extra debug lines to "Guru-MapEditor.log" for the next build to narrow down the call that causes the driver to crash.  With no Guru-Crash LOG or DMP I would not get a specific cause, only that the driver did not like a particular request and decided to reset, and MAX can detect this device reset and place "DEBUG: Device Lost: Reason code 0x887A0006" in the log.  Will be in the next DEVTEST build

**Comment by LeeBamberTGC** [comment]
@boltactiongaming I used a little AI help to submit all the code paths from the point the driver stalled to see if there was a GPU touch point that 'might' be the cause, and so I have added an extra flag to the SETUP.INI file called "disablejustgrasssystem". If you add "disablejustgrasssystem=1" so this file and launch MAX and try again with your steps to cause the crash, and it avoids the crash, then I have a pretty good idea what might be the cause of this on your AMD card.  In the new DEVTEST build just uploaded.

**Comment by boltactiongaming** [comment]
I changed that setting and this time it crashed as soon as it loaded the demo games (before it even loaded the project list).
Same situation; it crashed my video driver, no crash from GGM.  So unfortunately I didn't even get to the point of trying the terrain fix :\

[Guru-MapEditor.log](https://github.com/user-attachments/files/24768788/Guru-MapEditor.log)

**Comment by LeeBamberTGC** [comment]
@boltactiongaming And does it return to the earlier behavior when you set the flag back to zero?

**Comment by boltactiongaming** [comment]
Yes, same behavior as before if I toggle the flag.
Updated maplog:

[Guru-MapEditor.log](https://github.com/user-attachments/files/24801439/Guru-MapEditor.log)

**Comment by LeeBamberTGC** [comment]
@boltactiongaming I have added a fix to the last debug flag so that "disablejustgrasssystem=1" in SETUP.INI will now actually work when you run GameGuruMAX.exe from the latest DEVTEST build.  It was ignored before. Can I confirm that this crash-less driver freeze happens when you launch GameGuruMAX and then try to create a new level with a terrain generator accepting a height map. If so, can you attach (or email) that height map file so I can reproduce at this end to see if there is any corruption (along with the settings you may add to the terrain generator right panel properties panel when submitting the height map).  New DEVTEST build uploaded.

**Comment by boltactiongaming** [comment]
@LeeBamberTGC 
Ok, didn't crash on startup at least :)
Unfortunately same behavior persists:
1) New level
2) import heightmap
3) change scale
4) Change height value outside heightmap from -2000 to literally anything else
5) crashes
6) typical error, white screen, no crashdump initiating now

enclosed is maplog file


[Guru-MapEditor-last.log](https://github.com/user-attachments/files/24840531/Guru-MapEditor-last.log)

**Comment by LeeBamberTGC** [comment]
@boltactiongaming The "Guru-MapEditor-last.log" is simply a copy of an earlier LOG file, any chance you can attach the "Guru-MapEditor.log" file?  Also the heightmap file you are using, too, thanks!

**Comment by boltactiongaming** [comment]
[Guru-MapEditor.log](https://github.com/user-attachments/files/24840622/Guru-MapEditor.log)

I sent the last log because I accidentally reopened it again, so this one should look fine.

Also file was included earlier but here's another copy.

<img width="3646" height="1958" alt="Image" src="https://github.com/user-attachments/assets/cb44f0ff-ddeb-4149-a70b-99b654f3c0ae" />

**Comment by LeeBamberTGC** [comment]
@boltactiongaming New DEVTEST build uploaded with some tweaks to the crash debugging info but nothing specific on your issue but still worth a try in case we nudged something. I tried on my PC with your steps to reproduce, and was able to get past the crash step, to see this:

<img width="2583" height="1256" alt="Image" src="https://github.com/user-attachments/assets/1fb840f3-012a-4f1d-b450-855ee04879f8" />

Can you look at the parameters and see if you can spot anything significantly different about what I have set up?  As you can see I kept grass on to get a provocation but no joy. Also notice VRAM at just 2.65, curious what yours is at this point (choosing Rainforest and the following settings below):

<img width="647" height="1319" alt="Image" src="https://github.com/user-attachments/assets/6d933d1c-7272-4779-9361-1a59550e78cb" />

I also created a standalone of the result in case it can be reproduced on your PC in this way too: https://drive.google.com/file/d/1wuqFXrVAF0EfS4NDXm1kBskO0VXZHYhN/view?usp=sharing

**Comment by boltactiongaming** [comment]
default settings when entering.
Sometimes it takes a few flicks of settings to replicate.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/d46680bb-a2cb-4d64-a565-16f67bf4e866" />

Input image + resize:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/716818b0-e3d7-4546-9598-f8a233c67426" />

Adjusting HV outside HM:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/53be9d2b-cfaa-495f-86ee-48b7bcae9c36" />

No crash. Tried multiple times.
Attempting other settings, because this is an unpredictable issue - moving to water:
Adjusted water, worked for 2s then crashed:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/0bf4d6d7-3f15-44ee-bfc7-2246018d98de" />

Still not generating a crashdump.
Just sits on blank white screen.

[Guru-MapEditor.log](https://github.com/user-attachments/files/24841555/Guru-MapEditor.log)

So.. looking at the log file my guess is it's crashing the driver, but not the actual program. This *IS* a notable improvement to this point vs previous. So whatever your doing is slowly improving with each iteration.

**Comment by LeeBamberTGC** [comment]
@boltactiongaming Can you go into some details for a step by step on how you "Adjusted water, worked for 2s then crashed:" as it would be ideal if I can get my AMD card to crash also :)  Failing a repro at my end, the next step will probably be to set up some kind of monitoring of the GPU events until the crash, then send that GPU events log so we can narrow down the events that stall/fail/etc.  Are you familiar with tools such as PIX/RenderDoc/Intel GPA?

**Comment by boltactiongaming** [comment]
@LeeBamberTGC Not familiar with those tools, will try to look into it in the next day or so here. What do you prefer?
Also, all I did was go to the water height and move it up and down a few times.

**Comment by LeeBamberTGC** [comment]
Renderdoc is pretty cool

**Comment by boltactiongaming** [comment]
not sure if I did this right, but give it a whirl:
https://drive.google.com/file/d/1Rfnzi5_V91EwD_Y3MsRcJF04AyhMFi6W/view?usp=sharing

https://drive.google.com/file/d/1EhOvWOC6yQ6ogMRqj49fI_FzWkseoQ7N/view?usp=sharing

one was before, one was i think during a crash

**Comment by LeeBamberTGC** [comment]
@boltactiongaming Thanks for this!  The RenderDoc confirms all the GPU event submissions were successful, and the driver reset happens inside the Present() call, so triggers inside the driver.  We can now move onto the tool that can trace each frame until this happens, called GPUView (part of the Windows SDK).  If you can, follow these instructions and let me know if you need help:

Windows Performance Recorder
============================

Install Windows Performance Toolkit (comes with Windows SDK)

Run MAX and get to a point JUST BEFORE you trigger the driver reset.

In Windows, type CMD into your RUN command line, then run:

wpr -start GPU -filemode

In MAX, reproduce the freeze by sliding water height/etc. Wait for driver reset.

Back in the CMD Window, run:

wpr -stop gpu_trace.etl

Now send the file that was produced "gpu_trace.etl" (should be in :\Windows\system32) via email.

I can then open it with GPUView.exe :)

**Comment by boltactiongaming** [comment]
@LeeBamberTGC So I was able to reproduce the freeze using the trace and ALSO got a crash dump for the first time in several iterations. Not sure why that happened, so I'm including all of them:

[Guru-Crash.log](https://github.com/user-attachments/files/24847249/Guru-Crash.log)
[Guru-MapEditor.log](https://github.com/user-attachments/files/24847251/Guru-MapEditor.log)
[crashdump.dmp](https://github.com/user-attachments/files/24847250/crashdump.dmp)

https://drive.google.com/file/d/1D6HyMBwlpkkuBSmdUF_6srz5X8CcLwZ3/view?usp=sharing < the gpu trace

**Comment by LeeBamberTGC** [comment]
✅ Forwarded to: https://github.com/Dark-Basic-Software-Limited/GameGuruMAX/issues/141

Included the latest crash report comment with attachments/links.

**Comment by LeeBamberTGC** [comment]
✅ Forwarded to: https://github.com/Dark-Basic-Software-Limited/GameGuruMAX/issues/142

Included the latest crash report comment with attachments/links.

**Comment by LeeBamberTGC** [comment]
@boltactiongaming New DEVTEST build with a small tweak to the terrain system and a larger addition of PIX support.  If you still get the driver lost issue, follow these general steps and email me the resulting trace file. From this I can pinpoint where the stall is :)

1. Download and install PIX: https://devblogs.microsoft.com/pix/download/
2. Run and configure to launch MAX:
<img width="2415" height="1157" alt="Image" src="https://github.com/user-attachments/assets/ca47db72-f201-43c0-b04a-6d3f693f1d64" />
3. Go to the point just before the crash:
<img width="2642" height="1259" alt="Image" src="https://github.com/user-attachments/assets/e58ba8fe-6bea-46c1-b005-a2ffbc553986" />
4. Start the trace recording:
<img width="3387" height="774" alt="Image" src="https://github.com/user-attachments/assets/dda89866-3dbd-4dc0-bffe-686dad32058b" />
5. When the driver fails, stop the recording.
6. Save WPIX and send to me :)

<img width="654" height="314" alt="Image" src="https://github.com/user-attachments/assets/8ad3655b-5d89-4378-bbff-6d31fa67366b" />

**Comment by LeeBamberTGC** [comment]
@boltactiongaming I have reverted the DEVTEST build mentioned above as another user had issues, so you can now find a new build called EARLYTEST. If you switch to this one before you do the above instructions to produce the GPU trace, that would be great, thanks!

**Comment by boltactiongaming** [comment]
@LeeBamberTGC what's the code for Earlytest?

**Comment by LeeBamberTGC** [comment]
No password required:

<img width="1442" height="613" alt="Image" src="https://github.com/user-attachments/assets/3bfa531a-de98-43d1-8003-aee883de2661" />

**Comment by boltactiongaming** [comment]
I think I did this right?
https://drive.google.com/file/d/1DnF31X2XDMjLoPEKsOtM2_xe_4iAhdlo/view?usp=sharing

**Comment by LeeBamberTGC** [comment]
@boltactiongaming Yes, you did it right :)  It looks like a 13-second stall towards the end. The next time you provide the file, if you can include the LOG files too, that will give me an engine perspective to compare with the GPU trace:

<img width="3435" height="1273" alt="Image" src="https://github.com/user-attachments/assets/796396e4-6c4e-4645-a515-ac9f84386856" />

I assume when you ran this, you had "disablejustgrasssystem=0". Can you try it again with "disablejustgrasssystem=1" so we can remove all usage of GGGrass and see if that resolves the issue, and additionally, pinpoints the GPU issue to the grass system?

**Comment by boltactiongaming** [comment]
Last time this legitimately nuked my PC. I had to add new thermal paste to my CPU, it got so hot.
I'm going to try again here.
Unfortunately it doesn't seem to record. Not only did I not get a crash error this time, but PIX locked up and wouldn't actually let me stop the capture. I end tasked it, but no go.

[Guru-MapEditor.log](https://github.com/user-attachments/files/25055121/Guru-MapEditor.log)

This is all I have from that event. :/ I will try again. @LeeBamberTGC

**Comment by boltactiongaming** [comment]
@LeeBamberTGC Ok, I had to turn off hardware rendering for PIX's UI, that fixed it.
So here's the updated timing. pix file: https://drive.google.com/file/d/1g_gpuBdqoyyiNYkC9FHRN7AEhYHFGKNS/view?usp=sharing

updated map log
no crash available, didn't crash :\

[Guru-MapEditor.log](https://github.com/user-attachments/files/25055330/Guru-MapEditor.log)

**Comment by LeeBamberTGC** [comment]
@boltactiongaming Looks like the capture was good, though it did not contain too much GPU stuff, looking into that now. In the meantime AI was able to pick up a few clues from the CPU side activity, so a new EARLYTEST build has been uploaded with some guards around the function code that might be causing this. If you still get a driver device lost issue, follow these instructions so you can send me the output debugview log thaty this new guard code will produce:

Capture Debug Output Using DebugView
=====================
1. Download DebugView Go to: https://learn.microsoft.com/en-us/sysinternals/downloads/debugview
2. Click the Download DebugView link
3. Save the zip file to your computer
4. Right-click the downloaded DebugView.zip file
5. Select Extract All... and choose a location (e.g., your Desktop)
6. Open the extracted folder
7. Right-click on Dbgview64.exe (use Dbgview.exe if on 32-bit Windows)
8. Select Run as administrator (this is required to capture all debug output)
9. Once DebugView opens, go to the Capture menu
10. Ensure these options are checked: Capture Win32 and Capture Global Win32 (requires admin)
11. Go to Edit menu and click Clear Display to start fresh
12. Keep DebugView running in the background
13. Launch GameGuru MAX normally
14. Perform the actions that cause the crash/hang
15. DebugView will display messages in real-time
16. When the issue occurs (or just before if possible), switch back to DebugView
17. Go to File → Save As...
18. Save the log file as debugview_log.txt
19. Send this file for analysis

**Comment by boltactiongaming** [comment]
@LeeBamberTGC  
[ggm.log](https://github.com/user-attachments/files/25153745/ggm.log)

[Guru-MapEditor.log](https://github.com/user-attachments/files/25153749/Guru-MapEditor.log)

No crash dump this time.
I don't know why it's inconsistent about crash dumping these days.
Same process as usual (Load heightmap, change scale, change heightmap size outside terrain --> instant crash)
Didn't see anything outstanding in the debugview log :\

**Comment by LeeBamberTGC** [comment]
@boltactiongaming The GGM log was useful, and shows where what the command list sent off last to the GPU before all device lost hell broke loose! I suspect if we eliminate all 'treeness' from your next run, we might see progress when it comes to heightmap handling: 

00000257	49.71477127	[1788] GGTrees_Update DIAG: frame=500, numTreeTypes=38, numTreeChunks=256, totalInstancesProcessed=0, totalShadowTrees=0, lodDistShadow=2500.0	

I know it sounds a bit daft, but can you try setting SETUP.INI to read as "disableterrainsystem=1"?  It basically SKIPS alot of the terrain stuff including trees. Curious to know what your results would be!

**Comment by boltactiongaming** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/96da119a-af2a-46e6-96ef-eb311e833ede" />

@LeeBamberTGC  
This is what I see. I could not get it to crash, despite my best efforts.
I enclosed the map log and the  debugview log. Obviously I can't see what I'm doing either, but still, it didn't crash.

[Guru-MapEditor.log](https://github.com/user-attachments/files/25156553/Guru-MapEditor.log)

[ggm.log](https://github.com/user-attachments/files/25156549/ggm.log)

**Comment by LeeBamberTGC** [comment]
@boltactiongaming Just an update for you.  It is highly likely this will be resolved with the DX12 work that has already found some areas that relate to this section of the engine.  Thanks for your patience, I can hopefully send you a DX12 proto at some point to confirm the solution.

**Comment by LeeBamberTGC** [comment]
@boltactiongaming Just a quite update that I have terrain 'sort of' working in DX12 so proceeding well and should have something to test once I get the performance and tweaks sorted, at least for this terrain heightmap import step.  In the meantime, as I investigate a possible DX11 fix (as some users will want to remain on the DX11 version I suspect), can you switch the BIOME to Desert and switch trees off (after restoring ), and then importing a terrain heightmap. If this also works without crashing/freezing, then it is possible the 'quantity' of trees being processed in Terrain Generator was the cause of this.

<img width="1590" height="690" alt="Image" src="https://github.com/user-attachments/assets/9c37f2f0-3db7-45c3-8e79-0f5717e41f0f" />

Knowing that, some kind of 'slow and steady' approach to tree handling in the Terrain Generator might be a good forward step for DX11 version.
